### ISSUE TITLE
Text of written book disappears when you place it

### ISSUE THREAD

**Issue by mgl512** [everamzah/books#2] opened 2017-04-08 09:44 UTC
When you write a book and place it, it becomes a book node with no text. And a blank book when you break the node. The text is lost. It used to work and still works on the Axinite server.

**Comment by taikedz** [comment] 2017-04-15 08:17
Cannot reproduce this on 0.4.15-f8ad01a. My steps:

* create book as player1
* place book
* write in book
* pick up book
* place book -- see that text is still present

then

* log in as player2
* check player1's book -- see text
* pick up book
* read book - is OK
* place book - is OK

If you are seeing a different effect, please detail what you are doing. Please test on a new world with no other mods. If it works then, consider adding extra mods until the issue arises, Let me know what mod it was that broke it.

**Comment by mgl512** [comment] 2017-04-15 14:47
The steps you describe work in singleplayer and on a server. What works on Axinite but not in singleplayer with recently updated mt_game and 0.4.15-dev client/server is that, on Axinite, you can write a blank book in your hand, place it and see that the text is preserved. In a singleplayer game with books as the only mod, if you write a blank book in your hand and place it, the text is lost.

**Comment by taikedz** [comment] 2017-04-19 08:11
I can reproduce now, thanks. Will look into it.

**Comment by taikedz** [comment] 2017-04-19 18:11
Should be all fixed with https://github.com/taikedz/everamzah-books/commit/ba15809a38fd67bb89784973809948d027009b01

**Closed as completed** 2017-04-20 18:40 UTC

**Comment by mgl512** [comment] 2017-04-21 07:25
Thanks. We will test it on the server (Mynetest) soon. Works in singleplayer and on a copy of the server. I got several complains about the pencil and may write an issue about it.

**Comment by taikedz** [comment] 2017-04-21 12:58
If there are issues with the magic pencil then please do raise an issue.

I just pushed a change to make them optional btw, `mineetst.conf` will need an update setting
